name: Web Export and Deploy

on:
  push:
    branches: ['*'] 

jobs:
  deploy-web:
    steps:
      - run: eas/checkout
      - run: eas/install_node_modules
      - run: npx expo export --platform web
      - run: eas deploy