name: Web Export and Deploy

on:
  push:
    branches: ['*'] 

jobs:
  deploy-web:
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Export web build
        run: npx expo export --platform web
      - name: Deploy with EAS
        run: eas deploy
